<a href="https://colab.research.google.com/github/jiruneko/ML_inpress/blob/main/ML_impress.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd

In [20]:
data = {
    '松田の労働時間': [160, 150],
    '浅木の労働時間': [161, 175]
}

df = pd.DataFrame(data)
df

   松田の労働時間  浅木の労働時間
0      160      161
1      150      175

In [21]:
print(type(df))
df.shape

<class 'pandas.core.frame.DataFrame'>

(2, 2)

In [22]:
df.index = ['4月', '5月']
df

    松田の労働時間  浅木の労働時間
4月      160      161
5月      150      175

In [23]:
df.columns = ['松田の労働時間(h)','浅木の労働時間(h)']
df

    松田の労働時間(h)  浅木の労働時間(h)
4月         160         161
5月         150         175

In [24]:
df = pd.read_csv('KvsT.csv')

df.head(3)

    身長  体重  年代    派閥
0  170  60  10   きのこ
1  172  65  20   きのこ
2  170  60  30  たけのこ

In [25]:
df['身長']

0     170
1     172
2     170
3     170
4     177
5     168
6     169
7     170
8     180
9     170
10    165
11    170
12    175
13    170
14    170
15    155
16    160
17    170
18    175
Name: 身長, dtype: int64

In [27]:
xcol = ['身長', '体重', '年代']
x = df[xcol]
x

     身長  体重  年代
0   170  60  10
1   172  65  20
2   170  60  30
3   170  65  40
4   177  65  10
5   168  55  20
6   169  65  30
7   170  62  40
8   180  70  10
9   170  68  20
10  165  65  40
11  170  72  20
12  175  77  40
13  170  65  30
14  170  65  30
15  155  56  20
16  160  56  20
17  170  65  40
18  175  60  20

In [28]:
t = df['派閥']
t

0      きのこ
1      きのこ
2     たけのこ
3      きのこ
4     たけのこ
5      きのこ
6     たけのこ
7     たけのこ
8     たけのこ
9      きのこ
10    たけのこ
11     きのこ
12    たけのこ
13    たけのこ
14    たけのこ
15     きのこ
16    たけのこ
17     きのこ
18    たけのこ
Name: 派閥, dtype: object

In [29]:
from sklearn import tree

In [31]:
# モデルの準備
model = tree.DecisionTreeClassifier(random_state = 0)

# 学習の実行（x、tは事前に定義済みの特徴量と正解ラベル）
model.fit(x, t)

DecisionTreeClassifier(random_state=0)

In [32]:
taro = [[170, 70, 20]]
taro_df = pd.DataFrame(taro,
                       columns=x.columns)

model.predict(taro_df)

array(['きのこ'], dtype=object)

In [35]:
matsuda = [172, 65, 20]
asagi = [158, 48, 20]
new_data=pd.DataFrame([matsuda,asagi]
                      ,columns=x.columns)

model.predict(new_data)

array(['きのこ', 'たけのこ'], dtype=object)

In [36]:
model.score(x, t)

1.0

In [37]:
import pickle

with open('KinokoTakenoko.pkl', 'wb') as f:
  pickle.dump(model, f)

In [39]:
import pickle
with open('KinokoTakenoko.pkl', 'rb') as f:
  model2 = pickle.load(f)

In [40]:
suzuki = pd.DataFrame([[180, 75, 30]], columns=['身長', '体重', '年代'])
model2.predict(suzuki)

array(['たけのこ'], dtype=object)